# Generated by Django 3.0 on 2020-11-28 17:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.CharField(max_length=2083)),
                ('nbMembers', models.IntegerField()),
                ('description', models.CharField(max_length=2083)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('date', models.DateTimeField()),
                ('shortDescription', models.CharField(max_length=100)),
                ('event_img', models.CharField(max_length=2083)),
                ('team', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), default=list, size=None)),
                ('local', models.CharField(max_length=80)),
                ('longDescription', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
                ('event_img', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_img', models.CharField(max_length=2083)),
                ('facebook', models.CharField(max_length=2083)),
                ('github', models.CharField(max_length=2083)),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=25)),
                ('clubJoined', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('verfied', models.BooleanField()),
                ('_class', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
            ],
        ),
    ]
