# Generated by Django 3.0 on 2020-11-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='pic_url',
            field=models.CharField(default=1, max_length=2083),
            preserve_default=False,
        ),
    ]
